<?php
$labels = array();
$labels['pluginname'] = 'Attach vCard';
$labels['plugindescription'] = 'Attach your vCard to outgoing messages.';
$labels['attachvcard'] = 'Attach vCard';
$labels['from'] = 'Use vCard data from ...';
$labels['warning'] = 'Please note: When selecting the "Contact" option you will be sending private information with your vCard such as your birthday, private phone, mobile, photo, etc. Make sure to fill out your vCard\'s contact details only with the information you are willing to share before sending out your vCard attached to emails.';